const listaComponentes_formsts = ["list", "table", "playlist", "carrossel", "form", "map", "slideshow", "grafico", "pdf", "link", "texto", "image", "svg", "contact", "product", "dashboard", "audio", "video", "PList", "timeline", "BlogCard", "plans", "3DText", "Ad", "VirtualCard", "VirtualCreditCard", "Profile", "Sorteio", "Participants", "Calendar"];

function fcas_lightbox_generarListaSuportados(opcoes) { if (!opcoes) { return ""; } var lista = opcoes.lista; var separador = opcoes.separador; var ordemAlfabetica = opcoes.ordemAlfabetica; if (!lista || !Array.isArray(lista) || lista.length === 0) { return ""; } if (separador === undefined || separador === null || separador === "") { separador = ", "; } else if (String(separador).slice(-1) !== " ") { separador = separador + " "; } var listaFinal = lista.slice(); if (ordemAlfabetica) { listaFinal.sort(function(a, b) { return String(a).localeCompare(String(b)); }); } return listaFinal.join(separador); }
function fcas_lightbox_verificarTexto(texto) { return (texto && texto.trim() !== "") ? texto : ""; }

function fcas_lightbox_verificaranalisar(lista, idioma) { var c = 0; for (var i = 0; i < lista.length; i++) { if (lista[i] !== '' && lista[i] !== null && lista[i] !== undefined) { c++; } } if (c === 0) { return ''; } if (idioma === 'pt') { return 'Quantidade de tipos suportados: ' + c + '.'; } else { return 'Quantity of supported types: ' + c + '.'; } }


window.getDocData = function(fdd) {
    return {
        pt: {
            demoUrl: "/",
            title: "Lightbox - Conteúdos Diversos",
            subtitle: "Documentação Técnica",
            versionLabel: "Versão: ",
            playerLabel: "Player Embutido: ",
            playerValue: "Versão Mais Recente",
            btnText: "Ver Funcionando",
            info: "O Lightbox é uma ferramenta inovadora que oferece uma experiência integrada de forma intuitiva e moderna. Com uma interface limpa e responsiva, o aplicativo permite aos usuários explorar qualquer tipo de conteúdo de maneira eficiente, proporcionando uma navegação fluida e envolvente. Além disso, o Lightbox sempre será gratuito e conta com uma instalação extremamente fácil em qualquer site. Você também não precisa se preocupar com conflitos de design: o nosso estilo visual não interfere na sua página, pois o CSS é totalmente isolado e tudo passa por uma verificação prévia para garantir que nenhuma estilização original do seu site seja sobrescrita.",
            sectionTitle: "Documentação em Português",
            sectionDesc: "Esta página descreve o funcionamento do componente Lightbox para exibição de conteúdos diversos de forma responsiva em qualquer dispositivo.",
            sectionInit: "Para inicializar o componente, utilize a função global fsmodal_open(config) passando as opções estruturadas no formato de objeto abaixo:",
            legendGlobal: "Parâmetros Globais e Callbacks (content.config)",
            legendTypes: "Configuração de Tipos dentro de content.config",
            legendContext: "Estruturas de Dados Aceitas em content.context",
            legendOther: "content (Outros Parâmetros de Entrada)",
            base: [
                ['id', 'String com o ID do elemento contêiner onde o modal será inserido.'],
                ['wait', 'Número (ex: 3000) que define o tempo de espera em milissegundos antes de abrir o LightBox.'],
                ['isAdult', 'Se for true, o acesso ao conteúdo do modal só é permitido se o usuário comprovar que é maior de idade.'],
                ['age', 'Se isAdult for true, é obrigatório passar o age em número. O valor deve estar entre os limites de 10 a 76 anos (caso contrário, o padrão será 18 anos).'],
                ['scroll_hide', 'Se definido como "yes", oculta a barra de rolagem da página quando ativo.'],
                ['noclose', 'Se for true, esconde o botão de fechar e bloqueia o encerramento do modal.'],
                ['click_close', 'Se for true, fecha o lightbox ao clicar fora da área do conteúdo principal.'],
                ['remove_effect', 'Se definido como true, desativa as animações visuais de transição.'],
                ['size', 'String contendo apenas números (ex: "800") que define a largura máxima em pixels.'],
                ['loader', 'Se for true, mostra um spinner de carregamento enquanto o conteúdo é inserido.'],
                ['noprint', 'Se for true, ativa a proteção que esconde o conteúdo do modal ao tentar imprimir ou salvar a página.'],
                ['BG_Blur', 'String contendo apenas números que define a intensidade do efeito de desfoque de fundo (ex: "8").'],
                ['BG_Color', 'String contendo o código HEX da cor (ex: "#ff0055" ou "fff").'],
                ['BG_Opacity', 'String contendo apenas números decimais que define a opacidade de fundo do modal (ex: "0.9").'],
                ['tiptext', 'Opcional. String contendo um texto explicativo ou dica rápida associada à chamada do componente.'],
                ['include', 'Objeto contendo configurações adicionais, como { player: "yes" } para embutir o reprodutor de mídia.'],
                ['content', 'Objeto principal contendo as propriedades tratadas pela biblioteca.']
            ],
            global: [
                ['lang', 'Define o idioma da interface interna do componente, aceitando "pt" ou "en".'],
                ['onWait', 'Função de callback acionada enquanto aguarda o carregamento dos elementos ou dados do lightbox.'],
                ['onClose', 'Função de callback acionada no encerramento e remoção do lightbox.'],
                ['onOpen', 'Função de callback acionada na abertura e renderização do lightbox.'],
                ['onPlayer', 'Função de callback acionada quando o player de mídia interno realiza ações estruturais.'],
                ['onPlayer_Playlist', 'Função de callback acionada quando o player de mídia interno realiza ações estruturais relacionadas à lista de reprodução.'],
                ["onAdult", "Função de callback executada especificamente se isAdult for true, retornando 'yes' ou 'no'."]
            ],
            types: [
                ['Configuração para tipo: "texto"', 'Suporta as chaves de estilização direta: italic, negrito, upper, lower (booleanos), fontSize (número), color (string), textAlign (center,right,left,justify).'],
                ['Configuração para tipo: "list"', 'Suporta as chaves de formatatação estrutural: posicao (direita,esquerda), alinhamento (center,right,left,justify), tema, marcador (strings), arredondado (número), divisor (booleano).'],
                ['Configuração para tipo: "table"', 'Suporta as chaves de layout tabular: showIndex, zebra, headerBold (booleanos), align (center,right,left,justify), headerAlign (center,right,left,justify), model (string com chaves de colunas separadas por vírgula).'],
                ['Configuração para tipo: "playlist"', 'Suporta as chaves de controle de faixas: tema (string), exibirIndex (booleano).'],
                ['Configuração para tipo: "carrossel"', 'Suporta as chaves de controle do slider de mídia: tema (dark,light), transicao (slide,fade), posicaoDots (bottom), estiloDots (bolas,linhas,barras), intervalo (número), exibirControles, exibirDots, autoPlay (booleanos).'],
                ['Configuração para tipo: "grafico"', 'Suporta as chaves de renderização estatística: tema, orientacao (vertical ou horizontal), modelo (linha, pizza, barras), exibirValores, exibirTooltips (booleanos), larguraBarra, raioCurva (números).'],
                ['Configuração para tipo: "pdf"', 'Suporta o controle de foco do documento: page (número).'],
                ['Configuração para tipo: "image"', 'Suporta o controle de ampliação visual: scale (booleano), fit ("fill", "contain", "cover", "none", "scale-down").'],
                ['Configuração para tipo: "svg"', 'Suporta o controle de cor de vetores inline: fill, stroke (strings).'],
                ['Configuração para tipo: "map"', 'Suporta as chaves de dados: modelo [Aceita as opções: \'padrao\', \'brasil\', \'portugal\', \'mundo\' ou um caminho SVG customizado (\'M...\').], locais (array de objetos contendo nome, x, y, cor [código hex] e formato [circle, square]).'],
                ['Configuração para tipo: "contact"', 'Suporta as chaves de dados: nome, cargo, empresa, website, endereco, notas(strings), tema (escuro ou claro), telefones, emails (arrays) e redesSociais (objeto).'],
                ['Configuração para tipo: "product"', 'Suporta as chaves de dados: id, nome, codigoSku, descricao, valor, medida, moeda (strings), tema (escuro ou claro), precoOriginal, precoPromocional (números), imagens (array) e especificacoes (objeto).'],
                ['Configuração para tipo: "slideshow"', 'Suporta as chaves de estilização direta: effect ("slide", "fade", "zoom", "cube"), showControls (boolean), showCaptions (boolean).'],
                ['Configuração para tipos: "audio", "video" e "PList"', 'Suporta a parametrização completa de players de mídia: colorText, colorIcon, OSD_Pos, pos_time (strings), OSD_Lang ("pt"/"en"), OSD_Theme ("light"/"dark"), volume (número decimal), OSD_Time (número em ms), OSD, autoplay, mute, contextmenu, nocontrols (booleanos). Se OSD for true, suporta a propriedade OSD_Events (opcional) que aceita uma lista/array contendo eventos como: "exitfullscreen", "fullscreen", "end", "finish", "volume", "seek", "userseek", "unmute", "mute", "pause", "stop", "play", "speed", "previous", "next".'],
                ['Configuração Exclusiva para tipo: "PList"', 'Suporta adicionalmente a propriedade: select (string contendo apenas o número do item ativo da lista de reprodução).'],
                ['Configuração para tipo: "form"', 'Suporta o controle de validação e envio: method: (GET, POST, PUT, DELETE, PATCH), action (string), submitText, resetText (string), showReset (boolean), onsubmit (string, Nome da função de callback).']
            ],
            context: [
                ['Carrossel', 'Recebe um array de objetos contendo as chaves de caminhos e descrições: [ { url: "", legenda: "" } ]'],
                ['slideshow', 'Recebe um array de objetos contendo as chaves de caminhos e descrições: [ { url: "", caption: "" } ]'],
                ['Playlist', 'Recebe um array de objetos contendo as chaves de dados visuais e hiperlinks: [ { titulo: "", subtitulo: "", thumbnail: "", href: "" } ]'],
                ['texto', 'Recebe uma string simples contendo o texto normal.'],
                ['Tabela', 'Recebe um array contendo coleções de objetos estruturados com suas respectivas chaves e valores dinâmicos: [] dentro um objeto com keys e valores.'],
                ['Lista', 'Recebe um array de strings tradicionais contendo os itens sequenciais: [].'],
                ['audio', 'Recebe uma string contendo o link ou caminho URL direto do arquivo de áudio.'],
                ['link', 'Recebe uma string contendo a url do site externo de destino.'],
                ['video', 'Recebe uma string contendo o link ou caminho URL direto do arquivo de vídeo.'],
                ['pdf', 'Recebe uma string contendo a url do arquivo .pdf correspondente.'],
                ['image', 'Recebe uma string contendo o link ou caminho URL direto do arquivo de imagem.'],
                ['svg', 'Recebe uma string contendo o código XML/texto nativo completo do elemento estrutural: string do svg.'],
                ['grafico', 'Recebe um array contendo objetos estruturados com rótulos e seus valores numéricos reais: [ { label: "", valor: (number) } ]'],
                ['contact', 'Suporta chaves de dados de contato.'],
                ['product', 'Suporta chaves de dados do produto.'],
                ['map', 'Suporta chaves de dados do mapa.'],
                ['3DText','Recebe um objeto de configuração contendo as seguintes chaves: "text" (String) obrigatório para o texto que receberá o efeito tridimensional; "rotateX" (String) opcional para definir a inclinação vertical do card (ex: \'15deg\'); "rotateY" (String) opcional para definir a inclinação horizontal do card (ex: \'-15deg\'); "textColor" (String) opcional para a cor da face frontal do texto; "prefix" (String) opcional para customizar as classes CSS; "background" (String) para a cor ou gradiente de fundo; "borderRadius" (String) para o arredondamento das bordas; "boxShadow" (String) para a sombra do card; "maxWidth" (String) para a largura máxima; "fontFamily" (String) para a fonte; "padding" (String) para o espaçamento interno; "fontSize" (String) para o tamanho do texto no PC; e "mobileFontSize" (String) para o tamanho adaptivo no celular.'],
                ['Ad','Recebe um objeto de configuração contendo as seguintes chaves: "title" (String) obrigatório para o título do anúncio; "desc" (String) opcional para a descrição ou subtítulo promocional; "url" (String) opcional para o link de redirecionamento do botão de ação; "bgImage" (String) opcional para definir a URL da imagem de fundo do banner; "prefix" (String) opcional para customizar o nome das classes CSS; "badgeText" (String) para alterar o texto do selo (padrão \'Anúncio\'); "btnText" (String) para o texto do botão (padrão \'Saiba Mais\'); "background" (String) para a cor ou gradiente de fundo padrão caso não haja imagem; "borderRadius" (String) para o arredondamento das bordas; "boxShadow" (String) para a sombra do card; "maxWidth" (String) para a largura máxima; "height" (String) para a altura mínima do banner; "fontFamily" (String) para a tipografia; "padding" (String) para o espaçamento interno; "textColor" (String) para a cor das fontes gerais; "badgeBg" (String) para o fundo do selo; "badgeColor" (String) para a cor do texto do selo; "btnBg" (String) para o fundo do botão de ação; e "btnColor" (String) para a cor do texto do botão.'],
                ['VirtualCreditCard','Recebe um objeto de configuração contendo apenas as seguintes quatro chaves de dados: "holder" (String) obrigatório para definir o nome do titular; "type" (String) obrigatório para definir o estilo visual de cores (\'modern\', \'dark\', \'glass\', \'neon\' ou \'minimal\'); "chipImg" (String) opcional para passar a URL de uma imagem .png para o chip; e "label" (String) opcional para mudar o texto identificador do topo (que por padrão é \'Temporary\').'],
                ['VirtualCard','Recebe um objeto de configuração contendo as seguintes chaves: "name" (String) obrigatório para o nome; "role" (String) opcional para o cargo ou função; "avatar" (String) opcional para a URL da foto; "prefix" (String) opcional para customizar o nome das classes CSS; "type" (String) para definir o estilo visual de cores (aceita: \'modern\', \'dark\', \'glass\', \'neon\' ou \'minimal\'); "model" (String) para definir o formato estrutural do cartão (aceita: \'default\', \'badge\', \'compact\', \'avatar-top\' ou \'split\'); "items" (Array de Strings) contendo as informações de texto para a lista de contatos; "background" (String) para customizar a cor ou gradiente de fundo; "borderRadius" (String) para o arredondamento das bordas; "boxShadow" (String) para a sombra do card; "maxWidth" (String) para a largura máxima; "fontFamily" (String) para a fonte; "padding" (String) para o espaçamento interno; "textColor" (String) para a cor das fontes; "neonColor" (String) para a cor do brilho quando usado o tipo neon; e "splitColor" (String) para a cor do detalhe lateral quando usado o modelo split.'],
                ['Profile','Recebe um objeto de configuração contendo as seguintes chaves: "name" (String) para o nome obrigatório; "avatar" (String) para a URL opcional da imagem (vazio se não houver); "background" (String) para a cor de fundo; "borderRadius" (String) para o arredondamento das bordas; "textColor" (String) para a cor dos textos e abas; e "infos" (Array de Objetos) contendo "title" (String) para o título da aba e "content" (String).'],
                ['Sorteio','Recebe um objeto de configuração contendo as seguintes chaves: "title" (String) para o título do sorteio; "names" (Array de Strings) para a lista de nomes a serem sorteados; "numberMax" (Number) para o número máximo limite do sorteio numérico; "background" (String) para a cor de fundo do card; "borderRadius" (String) para as bordas arredondadas; "boxShadow" (String) para a sombra do card; "maxWidth" (String) para a largura máxima; "fontFamily" (String) para a fonte do texto; "padding" (String) para o espaçamento interno; "titleSize" (String) para o tamanho do título; "textColor" (String) para a cor do título; "resultSize" (String) para o tamanho do resultado; "resultColor" (String) para a cor do texto do resultado; "iconSize" (String) para o tamanho dos ícones SVG; e "iconColor" (String) para a cor dos ícones SVG.'],
                ['Participants','Recebe um objeto de configuração com: "title" (String) para o título; "background" (String) para o fundo; "borderRadius" (String) para as bordas; "boxShadow" (String) para a sombra; "maxWidth" (String) para a largura máxima; "fontFamily" (String) para a fonte; "padding" (String) para o espaçamento; "titleSize" (String) para o tamanho do título; "textColor" (String) para a cor dos textos; "statusColor" (String) para a cor do subtítulo do status; "iconSize" (String) para o tamanho dos ícones SVG; "iconColor" (String) para a cor do ícone confirmado; "pendingColor" (String) para a cor do ícone pendente; e "list" (Array de Objetos) onde cada participante possui "name" (String) obrigatório, "status" (String) opcional, "type" (String: \'confirmed\' ou \'pending\') para definir o ícone, e "avatar" (String) para a URL da foto (deixe vazio se não houver).'],
                ['Calendar','Recebe um objeto de configuração contendo as seguintes chaves: "title" (String) para o título do calendário; "prefix" (String) opcional para customizar o nome das classes CSS; "mode" (String) definindo a visualização entre \'week\', \'month\' ou \'year\'; "actual" (Boolean) se verdadeiro ativa a data atual do sistema automaticamente; "daysInMonth" (Number) quantidade de dias do mês; "activeDay" (Number) o dia atual a ser destacado; "days" (Array de Numbers) os dias da semana; "activeIdx" (Number) o índice do dia da semana a destacar; "months" (Array de Strings) os nomes dos meses; "activeMonth" (Number) o índice do mês a destacar; "background" (String) cor de fundo; "borderRadius" (String) arredondamento das bordas; "boxShadow" (String) sombra do card; "maxWidth" (String) largura máxima; "fontFamily" (String) fonte do texto; "padding" (String) espaçamento interno; "titleSize" (String) tamanho do título; "textColor" (String) cor do texto; "cellBg" (String) fundo das células; "headerColor" (String) cor do cabeçalho de dias; "activeColor" (String) cor de destaque do item ativo; e "iconSize" (String) tamanho do ícone SVG.'],
                ['timeline','Recebe um objeto contendo "data" (um array de objetos onde cada item possui as strings opcionais "date", "title", "description", ou chaves de categorias e botões como "nome" e "botoes") e "options" (um objeto opcional para configurar as strings de cores "color", "textColor" e "bgColor").'],
                ['BlogCard','Recebe um objeto com as chaves: title (string), text (string), image (string/URL da imagem), link (string/URL), linkText (string opcional), width (string opcional de tamanho, ex: \'400px\') e accentColor (string opcional de cor, ex: \'#hex\').'],
                ['plans','Recebe um objeto config com a chave plans (Array de Objetos), onde cada plano aceita as chaves title (String), price (String), features (Array de Strings), buttonText (String, opcional), link (String, opcional), popular (Boolean, opcional) e badgeText (String, opcional).'],
                ['dashboard','Recebe um único objeto de configuração estruturado com a string titulo, o objeto tema para customização de cores (fundoContainer, textoContainer, fundoHeader, borda, fundoConteudo, fundoCard, textoCard, valorCard, iconeCard, indicadorCard) e o array de objetos blocos para renderizar os cartões (nome, valor, indicador, svg).'],
                ['form', 'Configuração de campos suportando as chaves e tipos: [ {"label":"","name":"","required":"boolean","type":["text", "email", "password", "number", "tel", "url", "date", "textarea", "select", "range", "slider"],"placeholder":"","min":"number","max":"number","step":"number","options"::[{ value:"", label:"" }],"rows":"number"} ]'],
                ['PList', 'Recebe um array de objetos contendo o arquivo de áudio/vídeo, título e poster de capa correspondente: [ {"file":"","title":"","poster":""} ]']
            ],
            other: [
                ['title', 'String com o título que será exibido no topo do modal.'],
                ['type', 'Tipo do formato tratado ('+fcas_lightbox_verificarTexto(fdd || '')+').  '+fcas_lightbox_verificaranalisar(listaComponentes_formsts, "pt")+''],
                ['poster', 'URL da imagem de capa utilizada caso o tipo do conteúdo seja vídeo.'],
                ['description', 'Texto descritivo opcional posicionado junto ao bloco de conteúdo.']
            ]
        },
        en: {
            demoUrl: "/en",
            title: "Lightbox - Diverse Contents",
            subtitle: "Technical Documentation",
            versionLabel: "Version: ",
            playerLabel: "Embedded Player: ",
            playerValue: "Most Recent Version",
            btnText: "Live Demo",
            info: "Lightbox is an innovative tool that offers an integrated experience in an intuitive and modern way. With a clean and responsive interface, the application allows users to efficiently explore any type of content, providing fluid and engaging navigation. Furthermore, Lightbox will always be free and features an extremely easy installation on any website. You also don't have to worry about design conflicts: our visual style won't interfere with your page, as the CSS is completely isolated and everything goes through a prior verification to ensure that none of your website's original styling is overwritten.",
            sectionTitle: "English Documentation",
            sectionDesc: "This page describes the behavior of the Lightbox component for displaying diverse content responsively across all devices.",
            sectionInit: "To initialize the component, call the global function fsmodal_open(config) by passing an object structured with the following configurations:",
            legendGlobal: "Global Properties and Callbacks (content.config)",
            legendTypes: "Type Configurations inside content.config",
            legendContext: "Accepted Data Layout Structures in content.context",
            legendOther: "content (Other Input Parameters)",
            base: [
                ['id', 'String representing the ID of the container element where the modal attaches.'],
                ['wait', 'Number (e.g., 3000) that defines the waiting time in milliseconds before opening the LightBox.'],
                ['isAdult', 'If true, access to the modal content is only allowed if the user proves they are of legal age.'],
                ['age', 'If isAdult is true, it is mandatory to pass the age as a number. The value must be between the limits of 10 and 76 years old (otherwise, the default will be 18).'],
                ['scroll_hide', 'If set to "yes", it hides the main page scrollbar when the modal is active.'],
                ['noclose', 'If true, removes the close button and locks user interactions to prevent closing.'],
                ['click_close', 'If true, closes the lightbox view when performing click pointer triggers outside core bounding layout contents.'],
                ['remove_effect', 'If true, disables the visual transition effect animations.'],
                ['size', 'String containing numbers only (e.g., "800") which sets the maximum container width in pixels.'],
                ['loader', 'If true, displays a loading spinner while the content is being loaded.'],
                ['noprint', 'If true, activates the protection that hides the modal content when attempting to print or save the page.'],
                ['BG_Blur', 'String containing numbers only that defines the backdrop filter blur rendering strength (e.g., "8").'],
                ['BG_Color', 'String containing the HEX color code (e.g., "#ff0055" or "fff").'],
                ['BG_Opacity', 'String containing float numbers only that defines the backdrop container style opacity channel (e.g., "0.9").'],
                ['tiptext', 'Optional. String containing a tooltip phrase or helpful contextual instructions bound to the layout trigger.'],
                ['include', 'Object holding setup flags, like { player: "yes" } to append media rendering properties.'],
                ['content', 'Standard metadata wrapper object targeting libraries rendering pipeline.']
            ],
            global: [
                ['lang', 'Sets internal viewport translation dictionary mapping rules, accepting "pt" or "en".'],
                ['onWait', 'Callback function triggered while waiting for the lightbox elements or data to load.'],
                ['onClose', 'Callback function triggered upon termination and execution removal of the lightbox layout.'],
                ['onOpen', 'Callback function triggered upon viewport initialization and interface rendering of the lightbox layout.'],
                ['onPlayer', 'Callback function triggered when the underlying internal media engine issues state changes or structural updates.'],
                ['onPlayer_Playlist', 'Callback function triggered when the internal media player performs structural actions related to the playlist.'],
                ["onAdult", "Callback function executed specifically if isAdult is true, returning 'yes' or 'no'."]
            ],
            types: [
                ['Configuration for type: "texto"', 'Properties: italic, negrito, upper, lower (booleans), fontSize (number), color (string), textAlign (center,right,left,justify).'],
                ['Configuration for type: "list"', 'Properties: posicao (direita,esquerda), alinhamento (center,right,left,justify), tema, marcador (strings), arredondado (number), divisor (boolean).'],
                ['Configuration for type: "table"', 'Properties: showIndex, zebra, headerBold (booleans), align (center,right,left,justify), headerAlign (center,right,left,justify), model (comma-separated column target string).'],
                ['Configuration for type: "playlist"', 'Properties: tema (string), exibirIndex (boolean).'],
                ['Configuration for type: "carrossel"', 'Properties: tema (dark,light), transicao (slide,fade), posicaoDots (bottom), estiloDots (bolas,linhas,barras), intervalo (number), exibirControles, exibirDots, autoPlay (booleans).'],
                ['Configuration for type: "grafico"', 'Properties: tema, orientacao (vertical or horizontal), modelo (linha, pizza, barras), exibirValores, exibirTooltips (boolean), larguraBarra, raioCurva (numbers).'],
                ['Configuration for type: "pdf"', 'Properties: page (number).'],
                ['Configuration for type: "image"', 'Properties: scale (boolean), fit ("fill", "contain", "cover", "none", "scale-down").'],
                ['Configuration for type: "svg"', 'Properties: fill, stroke (strings).'],
                ['Configuration for type: "map"', 'Accepts an object with data keys: modelo [Accepts options: \'padrao\', \'brasil\', \'portugal\', \'mundo\' or a custom SVG path (\'M...\').], locais (array of objects containing nome, x, y, cor [hex code], and formato [circle, square]).'],
                ['Configuration for type: "contact"', 'Supports data keys: nome, cargo, empresa, website, endereco, notas (strings), tema (claro ou escuro), telefones, emails (arrays), and redesSociais (object).'],
                ['Configuration for type: "product"', 'Supports data keys: id, nome, codigoSku, descricao, valor, medida, moeda (strings), tema (claro ou escuro), precoOriginal, precoPromocional (numbers), imagens (array), and especificacoes (object).'],
                ['Configuration for type: "slideshow"', 'Properties: effect ("slide", "fade", "zoom", "cube"), showControls (boolean), showCaptions (boolean).'],
                ['Configuration for types: "audio", "video" and "PList"', 'Properties: colorText, colorIcon, OSD_Pos, pos_time (strings), OSD_Lang ("pt"/"en"), OSD_Theme ("light"/"dark"), volume (float), OSD_Time (number in ms), OSD, autoplay, mute, contextmenu, nocontrols (booleans). If OSD is true, it supports the OSD_Events (optional) property which maps an array collection tracking media events like: "exitfullscreen", "fullscreen", "end", "finish", "volume", "seek", "userseek", "unmute", "mute", "pause", "stop", "play", "speed", "previous", "next".'],
                ['Exclusive Configuration for type: "PList"', 'Properties: select (string tracking sequential track execution option array index number).'],
                ['Configuration for type: "form"', 'Supports validation and submission control: method: (GET, POST, PUT, DELETE, PATCH), action (string), submitText, resetText (string), showReset (boolean), onsubmit (string, Name of the callback function).']
            ],
            context: [
                ['Carousel', 'Accepts an array of objects carrying media paths and string text captions: [ { url: "", legenda: "" } ]'],
                ['slideshow', 'Accepts an array of objects carrying media paths and string text captions: [ { url: "", caption: "" } ]'],
                ['Playlist', 'Accepts an array of objects tracking graphic data and target navigation anchors: [ { titulo: "", subtitulo: "", thumbnail: "", href: "" } ]'],
                ['text', 'Accepts a clean and standard flat string payload: normal text string.'],
                ['Table', 'Accepts an array structure mapping collection sets of dynamic objects: [] containing an object with keys and values.'],
                ['List', 'Accepts a sequential collection array listing text strings: [].'],
                ['audio', 'Accepts a destination path string referencing an audio asset source file location: link.'],
                ['link', 'Accepts a navigation string target mapping a resource locator: website URL.'],
                ['video', 'Accepts a destination path string referencing a video asset source file location: link.'],
                ['pdf', 'Accepts a destination path string referencing a pdf document container: file URL.'],
                ['image', 'Accepts a destination path string referencing an image asset file location: link.'],
                ['svg', 'Accepts a source text string wrapping the raw inner XML vector definitions: svg string.'],
                ['chart', 'Accepts an array payload distributing labels against bound numeric values: [ { label: "", valor: (number) } ]'],
                ['contact', 'Supports contact data keys.'],
                ['product', 'Supports product data keys.'],
                ['map', 'Supports mapa data keys.'],
                ['3DText','Receives a configuration object containing the following keys: "text" (String) mandatory for the text that will receive the three-dimensional effect; "rotateX" (String) optional to set the vertical tilt angle of the card (e.g., \'15deg\'); "rotateY" (String) optional to set the horizontal tilt angle of the card (e.g., \'-15deg\'); "textColor" (String) optional for the font color of the front face; "prefix" (String) optional to customize CSS class names; "background" (String) for custom background color or gradient; "borderRadius" (String) for border radius; "boxShadow" (String) for shadows; "maxWidth" (String) for max width; "fontFamily" (String) for typography; "padding" (String) for internal padding; "fontSize" (String) for the text size on desktop; and "mobileFontSize" (String) for the adaptive text size on mobile screens.'],
                ['Ad','Receives a configuration object containing the following keys: "title" (String) mandatory for the advertisement title; "desc" (String) optional for the description or promotional subtitle; "url" (String) optional for the action button redirect link; "bgImage" (String) optional to define the banner background image URL; "prefix" (String) optional to customize CSS class names; "badgeText" (String) to change the badge text (defaults to \'Anúncio\'); "btnText" (String) for the button label (defaults to \'Saiba Mais\'); "background" (String) for custom background color or gradient if no image is provided; "borderRadius" (String) for border radius; "boxShadow" (String) for shadows; "maxWidth" (String) for max width; "height" (String) for the banner minimum height; "fontFamily" (String) for typography; "padding" (String) for internal padding; "textColor" (String) for general text color; "badgeBg" (String) for the top badge background color; "badgeColor" (String) for the badge text color; "btnBg" (String) for the action button background color; and "btnColor" (String) for the button text color.'],
                ['VirtualCreditCard','Receives a configuration object containing only the following four data keys: "holder" (String) mandatory to define the cardholder name; "type" (String) mandatory to define the visual color style (\'modern\', \'dark\', \'glass\', \'neon\', or \'minimal\'); "chipImg" (String) optional for a .png image URL for the chip; and "label" (String) optional to change the top identification text (which defaults to \'Temporary\').'],
                ['VirtualCard','Receives a configuration object containing the following keys: "name" (String) mandatory for the name; "role" (String) optional for the job title or role; "avatar" (String) optional for the image URL; "prefix" (String) optional to customize the CSS class names; "type" (String) to define the color visual style (accepts: \'modern\', \'dark\', \'glass\', \'neon\', or \'minimal\'); "model" (String) to define the card structural layout (accepts: \'default\', \'badge\', \'compact\', \'avatar-top\', or \'split\'); "items" (Array of Strings) containing text information for the contact list; "background" (String) to customize the background color or gradient; "borderRadius" (String) for the border radius; "boxShadow" (String) for the card box shadow; "maxWidth" (String) for the maximum width; "fontFamily" (String) for the text font family; "padding" (String) for the internal padding; "textColor" (String) for the text font color; "neonColor" (String) for the glow color when using the neon type; and "splitColor" (String) for the side border detail color when using the split model.'],
                ['Profile','Receives a configuration object containing the following keys: "name" (String) for the mandatory name; "avatar" (String) for the optional image URL (empty if none); "background" (String) for the CSS background color; "borderRadius" (String) for the CSS border radius; "textColor" (String) for the main text and active tab color; and "infos" (Array of Objects) containing "title" (String) for the tab title and "content" (String).'],
                ['Sorteio','Receives a configuration object containing the following keys: "title" (String) for the raffle title; "names" (Array of Strings) for the list of names to be drawn; "numberMax" (Number) for the maximum limit of the number draw; "background" (String) for the card background color; "borderRadius" (String) for the border radius; "boxShadow" (String) for the card box shadow; "maxWidth" (String) for the maximum width; "fontFamily" (String) for the text font family; "padding" (String) for the internal padding; "titleSize" (String) for the title font size; "textColor" (String) for the title text color; "resultSize" (String) for the result font size; "resultColor" (String) for the result text color; "iconSize" (String) for the SVG icons size; and "iconColor" (String) for the SVG icons color.'],
                ['Participants','Receives a configuration object with: "title" (String) for the title; "background" (String) for the background color; "borderRadius" (String) for border radius; "boxShadow" (String) for box shadow; "maxWidth" (String) for max width; "fontFamily" (String) for font family; "padding" (String) for padding; "titleSize" (String) for title size; "textColor" (String) for text color; "statusColor" (String) for the status subtitle color; "iconSize" (String) for the SVG icons size; "iconColor" (String) for the confirmed icon color; "pendingColor" (String) for the pending icon color; and "list" (Array of Objects) where each participant has mandatory "name" (String), optional "status" (String), "type" (String: \'confirmed\' or \'pending\') to define the icon, and "avatar" (String) for the image URL (empty if none).'],
                ['Calendar','Receives a configuration object containing the following keys: "title" (String) for the calendar title; "prefix" (String) optional to customize the CSS class names; "mode" (String) defining the view as \'week\', \'month\', or \'year\'; "actual" (Boolean) if true automatically enables the system\'s current date; "daysInMonth" (Number) total days in the month; "activeDay" (Number) the current day to highlight; "days" (Array of Numbers) the days of the week; "activeIdx" (Number) the week day index to highlight; "months" (Array of Strings) the names of the months; "activeMonth" (Number) the month index to highlight; "background" (String) background color; "borderRadius" (String) border radius; "boxShadow" (String) card box shadow; "maxWidth" (String) maximum width; "fontFamily" (String) text font family; "padding" (String) internal padding; "titleSize" (String) title font size; "textColor" (String) text color; "cellBg" (String) cells background color; "headerColor" (String) days header text color; "activeColor" (String) highlight color for the active item; and "iconSize" (String) SVG icon size.'],
                ['timeline','Receives an object containing "data" (an array of objects where each item has the optional strings "date", "title", "description", or category and button keys like "nome" and "botoes") and "options" (an optional object to configure the color strings "color", "textColor", and "bgColor").'],
                ['BlogCard','Receives an object with the keys: title (string), text (string), image (string/image URL), link (string/URL), linkText (optional string), width (optional size string, e.g., \'400px\'), and accentColor (optional color string, e.g., \'#hex\').'],
                ['plans','Receives an object with a plans key (Array of Objects), where each plan accepts the keys title (String), price (String), features (Array of Strings), buttonText (String, optional), link (String, optional), popular (Boolean, optional), and badgeText (String, optional).'],
                ['dashboard','Receives a single configuration object structured with the string titulo, the tema object for color customization (fundoContainer, textoContainer, fundoHeader, borda, fundoConteudo, fundoCard, textoCard, valorCard, iconeCard, indicadorCard), and the array of objects blocos to render the cards (nome, valor, indicador, svg).'],
                ['form', 'Fields configuration supporting the keys and types: [ {"label":"","name":"","required":"boolean","type":["text", "email", "password", "number", "tel", "url", "date", "textarea", "select", "range", "slider"],"placeholder":"","min":"number","max":"number","step":"number","options":[{ value:"", label:"" }],"rows":"number"} ]'],
                ['PList', 'Accepts a tracking playlist array carrying structural media source locations, title texts, and posters: [ {"file":"","title":"","poster":""} ]']
            ],
            other: [
                ['title', 'String value rendering the headline text at the top of the header.'],
                ['type', 'Evaluated payload type ('+fcas_lightbox_verificarTexto(fdd || '')+').  '+fcas_lightbox_verificaranalisar(listaComponentes_formsts, "en")+''],
                ['poster', 'URL string targeting thumbnail posters required when mapping videos.'],
                ['description', 'Complementary description text aligned beneath or near the asset render block.']
            ]
        }
    };
};
