window.getDocData = function() {
    return {
        pt: {
            demoUrl: "/",
            title: "Lightbox - Conteúdos Diversos",
            subtitle: "Documentação Técnica",
            versionLabel: "Versão: ",
            playerLabel: "Player Embutido: ",
            playerValue: "Versão Mais Recente",
            btnText: "Ver Funcionando",
            sectionTitle: "Documentação em Português",
            sectionDesc: "Esta página descreve o funcionamento do componente Lightbox para exibição de conteúdos diversos de forma responsiva em qualquer dispositivo.",
            sectionInit: "Para inicializar o componente, utilize a função global fsmodal_open(config) passando as opções estruturadas no formato de objeto abaixo:",
            legendGlobal: "Parâmetros Globais e Callbacks (content.config)",
            legendTypes: "Configuração de Tipos dentro de content.config",
            legendContext: "Estruturas de Dados Aceitas em content.context",
            legendOther: "content (Outros Parâmetros de Entrada)",
            base: [
                ['id', 'String com o ID do elemento contêiner onde o modal será inserido.'],
                ['isAdult', 'Se for true, o acesso ao conteúdo do modal só é permitido se o usuário comprovar que é maior de idade.'],
                ['scroll_hide', 'Se definido como "yes", oculta a barra de rolagem da página quando ativo.'],
                ['noclose', 'Se for true, esconde o botão de fechar e bloqueia o encerramento do modal.'],
                ['click_close', 'Se for true, fecha o lightbox ao clicar fora da área do conteúdo principal.'],
                ['remove_effect', 'Se definido como true, desativa as animações visuais de transição.'],
                ['size', 'String contendo apenas números (ex: "800") que define a largura máxima em pixels.'],
                ['loader', 'Se for true, mostra um spinner de carregamento enquanto o conteúdo é inserido.'],
                ['noprint', 'Se for true, ativa a proteção que esconde o conteúdo do modal ao tentar imprimir ou salvar a página.'],
                ['BG_Blur', 'String contendo apenas números que define a intensidade do efeito de desfoque de fundo (ex: "8").'],
                ['BG_Color', 'String contendo o código HEX da cor (ex: "#ff0055" ou "fff").'],
                ['BG_Opacity', 'String contendo apenas números decimais que define a opacidade de fundo do modal (ex: "0.9").'],
                ['tiptext', 'Opcional. String contendo um texto explicativo ou dica rápida associada à chamada do componente.'],
                ['include', 'Objeto contendo configurações adicionais, como { player: "yes" } para embutir o reprodutor de mídia.'],
                ['content', 'Objeto principal contendo as propriedades tratadas pela biblioteca.']
            ],
            global: [
                ['lang', 'Define o idioma da interface interna do componente, aceitando "pt" ou "en".'],
                ['onClose', 'Função de callback acionada no encerramento e remoção do lightbox.'],
                ['onOpen', 'Função de callback acionada na abertura e renderização do lightbox.'],
                ['onPlayer', 'Função de callback acionada quando o player de mídia interno realiza ações estruturais.'],
                ['onPlayer_Playlist', 'Função de callback acionada quando o player de mídia interno realiza ações estruturais relacionadas à lista de reprodução.']
            ],
            types: [
                ['Configuração para tipo: "texto"', 'Suporta as chaves de estilização direta: italic, negrito, upper, lower (booleanos), fontSize (número), color (string), textAlign (center,right,left,justify).'],
                ['Configuração para tipo: "list"', 'Suporta as chaves de formatatação estrutural: posicao (direita,esquerda), alinhamento (center,right,left,justify), tema, marcador (strings), arredondado (número), divisor (booleano).'],
                ['Configuração para tipo: "table"', 'Suporta as chaves de layout tabular: showIndex, zebra, headerBold (booleanos), align (center,right,left,justify), headerAlign (center,right,left,justify), model (string com chaves de colunas separadas por vírgula).'],
                ['Configuração para tipo: "playlist"', 'Suporta as chaves de controle de faixas: tema (string), exibirIndex (booleano).'],
                ['Configuração para tipo: "carrossel"', 'Suporta as chaves de controle do slider de mídia: tema (dark,light), transicao (slide,fade), posicaoDots (bottom), estiloDots (bolas,linhas,barras), intervalo (número), exibirControles, exibirDots, autoPlay (booleanos).'],
                ['Configuração para tipo: "grafico"', 'Suporta as chaves de renderização estatística: tema, orientacao (vertical ou horizontal), modelo (linha, pizza, barras), exibirValores, exibirTooltips (booleanos), larguraBarra, raioCurva (números).'],
                ['Configuração para tipo: "pdf"', 'Suporta o controle de foco do documento: page (número).'],
                ['Configuração para tipo: "image"', 'Suporta o controle de ampliação visual: scale (booleano), fit ("fill", "contain", "cover", "none", "scale-down").'],
                ['Configuração para tipo: "svg"', 'Suporta o controle de cor de vetores inline: fill, stroke (strings).'],
                ['Configuração para tipo: "contact"', 'Suporta as chaves de dados: nome, cargo, empresa, website, endereco, notas(strings), tema (escuro ou claro), telefones, emails (arrays) e redesSociais (objeto).'],
                ['Configuração para tipo: "product"', 'Suporta as chaves de dados: id, nome, codigoSku, descricao, valor, medida, moeda (strings), tema (escuro ou claro), precoOriginal, precoPromocional (números), imagens (array) e especificacoes (objeto).'],
                ['Configuração para tipo: "slideshow"', 'Suporta as chaves de estilização direta: effect ("slide", "fade", "zoom", "cube"), showControls (boolean), showCaptions (boolean).'],
                ['Configuração para tipos: "audio", "video" e "PList"', 'Suporta a parametrização completa de players de mídia: colorText, colorIcon, OSD_Pos, pos_time (strings), OSD_Lang ("pt"/"en"), OSD_Theme ("light"/"dark"), volume (número decimal), OSD_Time (número em ms), OSD, autoplay, mute, contextmenu, nocontrols (booleanos). Se OSD for true, suporta a propriedade OSD_Events (opcional) que aceita uma lista/array contendo eventos como: "exitfullscreen", "fullscreen", "end", "finish", "volume", "seek", "userseek", "unmute", "mute", "pause", "stop", "play", "speed", "previous", "next".'],
                ['Configuração Exclusiva para tipo: "PList"', 'Suporta adicionalmente a propriedade: select (string contendo apenas o número do item ativo da lista de reprodução).'],
                ['Configuração para tipo: "form"', 'Suporta o controle de validação e envio: method: (GET, POST, PUT, DELETE, PATCH), action (string), submitText (string), onsubmit (string).']
            ],
            context: [
                ['Carrossel', 'Recebe um array de objetos contendo as chaves de caminhos e descrições: [ { url: "", legenda: "" } ]'],
                ['slideshow', 'Recebe um array de objetos contendo as chaves de caminhos e descrições: [ { url: "", caption: "" } ]'],
                ['Playlist', 'Recebe um array de objetos contendo as chaves de dados visuais e hiperlinks: [ { titulo: "", subtitulo: "", thumbnail: "", href: "" } ]'],
                ['texto', 'Recebe uma string simples contendo o texto normal.'],
                ['Tabela', 'Recebe um array contendo coleções de objetos estruturados com suas respectivas chaves e valores dinâmicos: [] dentro um objeto com keys e valores.'],
                ['Lista', 'Recebe um array de strings tradicionais contendo os itens sequenciais: [].'],
                ['audio', 'Recebe uma string contendo o link ou caminho URL direto do arquivo de áudio.'],
                ['link', 'Recebe uma string contendo a url do site externo de destino.'],
                ['video', 'Recebe uma string contendo o link ou caminho URL direto do arquivo de vídeo.'],
                ['pdf', 'Recebe uma string contendo a url do arquivo .pdf correspondente.'],
                ['image', 'Recebe uma string contendo o link ou caminho URL direto do arquivo de imagem.'],
                ['svg', 'Recebe uma string contendo o código XML/texto nativo completo do elemento estrutural: string do svg.'],
                ['grafico', 'Recebe um array contendo objetos estruturados com rótulos e seus valores numéricos reais: [ { label: "", valor: (number) } ]'],
                ['contact', 'Suporta chaves de dados de contato.'],
                ['product', 'Suporta chaves de dados do produto.'],
                ['form', 'Configuração de campos suportando as chaves e tipos: [ {"label":"","name":"","required":"boolean","type":["text", "email", "password", "number", "tel", "url", "date", "textarea", "select", "range", "slider"],"placeholder":"","min":"number","max":"number","step":"number","options"::[{ value:"", label:"" }],"rows":"number"} ]'],
                ['PList', 'Recebe um array de objetos contendo o arquivo de áudio/vídeo, título e poster de capa correspondente: [ {"file":"","title":"","poster":""} ]']
            ],
            other: [
                ['title', 'String com o título que será exibido no topo do modal.'],
                ['type', 'Tipo do formato tratado (list, table, playlist, carrossel, form, slideshow, grafico, pdf, link, texto, image, svg, contact, product, audio, video, PList).'],
                ['poster', 'URL da imagem de capa utilizada caso o tipo do conteúdo seja vídeo.'],
                ['description', 'Texto descritivo opcional posicionado junto ao bloco de conteúdo.']
            ]
        },
        en: {
            demoUrl: "/en",
            title: "Lightbox - Diverse Contents",
            subtitle: "Technical Documentation",
            versionLabel: "Version: ",
            playerLabel: "Embedded Player: ",
            playerValue: "Most Recent Version",
            btnText: "Live Demo",
            sectionTitle: "English Documentation",
            sectionDesc: "This page describes the behavior of the Lightbox component for displaying diverse content responsively across all devices.",
            sectionInit: "To initialize the component, call the global function fsmodal_open(config) by passing an object structured with the following configurations:",
            legendGlobal: "Global Properties and Callbacks (content.config)",
            legendTypes: "Type Configurations inside content.config",
            legendContext: "Accepted Data Layout Structures in content.context",
            legendOther: "content (Other Input Parameters)",
            base: [
                ['id', 'String representing the ID of the container element where the modal attaches.'],
                ['isAdult', 'If true, access to the modal content is only allowed if the user proves they are of legal age.'],
                ['scroll_hide', 'If set to "yes", it hides the main page scrollbar when the modal is active.'],
                ['noclose', 'If true, removes the close button and locks user interactions to prevent closing.'],
                ['click_close', 'If true, closes the lightbox view when performing click pointer triggers outside core bounding layout contents.'],
                ['remove_effect', 'If true, disables the visual transition effect animations.'],
                ['size', 'String containing numbers only (e.g., "800") which sets the maximum container width in pixels.'],
                ['loader', 'If true, displays a loading spinner while the content is being loaded.'],
                ['noprint', 'If true, activates the protection that hides the modal content when attempting to print or save the page.'],
                ['BG_Blur', 'String containing numbers only that defines the backdrop filter blur rendering strength (e.g., "8").'],
                ['BG_Color', 'String containing the HEX color code (e.g., "#ff0055" or "fff").'],
                ['BG_Opacity', 'String containing float numbers only that defines the backdrop container style opacity channel (e.g., "0.9").'],
                ['tiptext', 'Optional. String containing a tooltip phrase or helpful contextual instructions bound to the layout trigger.'],
                ['include', 'Object holding setup flags, like { player: "yes" } to append media rendering properties.'],
                ['content', 'Standard metadata wrapper object targeting libraries rendering pipeline.']
            ],
            global: [
                ['lang', 'Sets internal viewport translation dictionary mapping rules, accepting "pt" or "en".'],
                ['onClose', 'Callback function triggered upon termination and execution removal of the lightbox layout.'],
                ['onOpen', 'Callback function triggered upon viewport initialization and interface rendering of the lightbox layout.'],
                ['onPlayer', 'Callback function triggered when the underlying internal media engine issues state changes or structural updates.'],
                ['onPlayer_Playlist', 'Callback function triggered when the internal media player performs structural actions related to the playlist.']
            ],
            types: [
                ['Configuration for type: "texto"', 'Properties: italic, negrito, upper, lower (booleans), fontSize (number), color (string), textAlign (center,right,left,justify).'],
                ['Configuration for type: "list"', 'Properties: posicao (direita,esquerda), alinhamento (center,right,left,justify), tema, marcador (strings), arredondado (number), divisor (boolean).'],
                ['Configuration for type: "table"', 'Properties: showIndex, zebra, headerBold (booleans), align (center,right,left,justify), headerAlign (center,right,left,justify), model (comma-separated column target string).'],
                ['Configuration for type: "playlist"', 'Properties: tema (string), exibirIndex (boolean).'],
                ['Configuration for type: "carrossel"', 'Properties: tema (dark,light), transicao (slide,fade), posicaoDots (bottom), estiloDots (bolas,linhas,barras), intervalo (number), exibirControles, exibirDots, autoPlay (booleans).'],
                ['Configuration for type: "grafico"', 'Properties: tema, orientacao (vertical or horizontal), modelo (linha, pizza, barras), exibirValores, exibirTooltips (boolean), larguraBarra, raioCurva (numbers).'],
                ['Configuration for type: "pdf"', 'Properties: page (number).'],
                ['Configuration for type: "image"', 'Properties: scale (boolean), fit ("fill", "contain", "cover", "none", "scale-down").'],
                ['Configuration for type: "svg"', 'Properties: fill, stroke (strings).'],
                ['Configuration for type: "contact"', 'Supports data keys: nome, cargo, empresa, website, endereco, notas (strings), tema (claro ou escuro), telefones, emails (arrays), and redesSociais (object).'],
                ['Configuration for type: "product"', 'Supports data keys: id, nome, codigoSku, descricao, valor, medida, moeda (strings), tema (claro ou escuro), precoOriginal, precoPromocional (numbers), imagens (array), and especificacoes (object).'],
                ['Configuration for type: "slideshow"', 'Properties: effect ("slide", "fade", "zoom", "cube"), showControls (boolean), showCaptions (boolean).'],
                ['Configuration for types: "audio", "video" and "PList"', 'Properties: colorText, colorIcon, OSD_Pos, pos_time (strings), OSD_Lang ("pt"/"en"), OSD_Theme ("light"/"dark"), volume (float), OSD_Time (number in ms), OSD, autoplay, mute, contextmenu, nocontrols (booleans). If OSD is true, it supports the OSD_Events (optional) property which maps an array collection tracking media events like: "exitfullscreen", "fullscreen", "end", "finish", "volume", "seek", "userseek", "unmute", "mute", "pause", "stop", "play", "speed", "previous", "next".'],
                ['Exclusive Configuration for type: "PList"', 'Properties: select (string tracking sequential track execution option array index number).'],
                ['Configuration for type: "form"', 'Supports validation and submission control: method: (GET, POST, PUT, DELETE, PATCH), action (string), submitText (string), onsubmit (string).']
            ],
            context: [
                ['Carousel', 'Accepts an array of objects carrying media paths and string text captions: [ { url: "", legenda: "" } ]'],
                ['slideshow', 'Accepts an array of objects carrying media paths and string text captions: [ { url: "", caption: "" } ]'],
                ['Playlist', 'Accepts an array of objects tracking graphic data and target navigation anchors: [ { titulo: "", subtitulo: "", thumbnail: "", href: "" } ]'],
                ['text', 'Accepts a clean and standard flat string payload: normal text string.'],
                ['Table', 'Accepts an array structure mapping collection sets of dynamic objects: [] containing an object with keys and values.'],
                ['List', 'Accepts a sequential collection array listing text strings: [].'],
                ['audio', 'Accepts a destination path string referencing an audio asset source file location: link.'],
                ['link', 'Accepts a navigation string target mapping a resource locator: website URL.'],
                ['video', 'Accepts a destination path string referencing a video asset source file location: link.'],
                ['pdf', 'Accepts a destination path string referencing a pdf document container: file URL.'],
                ['image', 'Accepts a destination path string referencing an image asset file location: link.'],
                ['svg', 'Accepts a source text string wrapping the raw inner XML vector definitions: svg string.'],
                ['chart', 'Accepts an array payload distributing labels against bound numeric values: [ { label: "", valor: (number) } ]'],
                ['contact', 'Supports contact data keys.'],
                ['product', 'Supports product data keys.'],
                ['form', 'Fields configuration supporting the keys and types: [ {"label":"","name":"","required":"boolean","type":["text", "email", "password", "number", "tel", "url", "date", "textarea", "select", "range", "slider"],"placeholder":"","min":"number","max":"number","step":"number","options":[{ value:"", label:"" }],"rows":"number"} ]'],
                ['PList', 'Accepts a tracking playlist array carrying structural media source locations, title texts, and posters: [ {"file":"","title":"","poster":""} ]']
            ],
            other: [
                ['title', 'String value rendering the headline text at the top of the header.'],
                ['type', 'Evaluated payload type (list, table, playlist, carrossel, form, slideshow, grafico, pdf, link, texto, image, svg, contact, product, audio, video, PList).'],
                ['poster', 'URL string targeting thumbnail posters required when mapping videos.'],
                ['description', 'Complementary description text aligned beneath or near the asset render block.']
            ]
        }
    };
};
